server:
  port: 8080

spring:
  application:
    name: user-service

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://alloy.monitoring.svc.cluster.local:4318
  prometheus:
    metrics:
      export:
        enabled: true

otel:
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://alloy.monitoring.svc.cluster.local:4318
      traces:
        endpoint: http://alloy.monitoring.svc.cluster.local:4318/v1/traces
      logs:
        endpoint: http://alloy.monitoring.svc.cluster.local:4318/v1/logs
      metrics:
        endpoint: http://alloy.monitoring.svc.cluster.local:4318/v1/metrics



