server:
  port: 8080

spring:
  application:
    name: user-service
  management:
    server:
      port: 8080
    endpoints:
      web:
        exposure:
          include: "*"
    metrics:
      export:
        prometheus:
          enabled: true
    endpoint:
      prometheus:
        enabled: true
    tracing:
      enabled: true
      sampling:
        probability: 1.0
      otlp:
        endpoint: http://alloy:4318
        protocol: http/protobuf



