server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/profile-db
    username: customer
    password: password
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate:
        envers:
          autoRegisterListeners: true
          audit_table_suffix: _history
          default_schema: profile_service_history
          store_data_at_delete: true
          revision_field_name: revision
          revision_type_field_name: revision_type
          revision_sequence_name: profile_service_history.revinfo_seq
        hibernate:
          default_schema: profile
          show_sql: ${SHOW_SQL:true}
          format_sql: ${FORMAT_SQL:true}
          highlight_sql: ${HIGHLIGHT_SQL:true}
          session.events.log.LOG_QUERIES_SLOWER_THAN_MS: ${SLOW_SQL_QUERY_INDICATOR_MS:1500}
          hbm2ddl:
            auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true

otel:
  exporter:
    otlp:
      endpoint: http://alloy.monitoring.svc.cluster.local:4318
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none



