name: build and publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          architecture: 'aarch64'
          distribution: 'adopt'
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
        run: ./gradlew bootBuildImage --imagePlatform linux/arm64
      - name: Tag & publish to GitHub Container Registry
        run: |
          VERSION=1.0.${{ github.run_number }}
          IMAGE_NAME=docker.io/library/user-service:1.0.0
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/docker.io/library/user-service:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID