name: build and publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
        run: ./gradlew bootBuildImage
      - name: Tag & publish to GitHub Container Registry
        run: |
          VERSION=1.0.0
          IMAGE_NAME=docker.io/library/user-service:$VERSION
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID